### ISSUE TITLE
Doesn't work with Alsa or Jack

### ISSUE THREAD

**Issue by dromer** [Jajcus/sampledrawer#1]
I don't have PA, so sampledrawer should be able to use at least plain Alsa.

**Comment by Jajcus** [comment]
Doesn't it? I have used the basic Qt media player and decoder, assuming it should 'just work' everywhere. I have not tested it with anything else than PulseAudio, though.

How exactly does it not work for you? Any error message?
Do you have audio in other Qt5 based applications?

**Comment by Jajcus** [comment]
I have added '--auto-device' command-line option. A quick hack, but maybe it helps.

**Comment by dromer** [comment]
By default it outputs:
```
PulseAudioService: pa_context_connect() failed
using null output device, none available
```

With `./sampledrawer --audio-device default` it does work with my default alsa device \o/

thnx!

Got some more feature requests, but nice project. Was looking for something like this.

**Comment by Jajcus** [comment]
I have added a new audio driver, using GStreamer instead of Qt multimedia capabilities. This should allow using ALSA, PulseAudio and Jack properly and any other audio sink supported by GStreamer.

To use ALSA:
./sampledrawer --audio-driver=gstreamer --audio-device='alsasink'

PuleAudio:
./sampledrawer --audio-driver=gstreamer --audio-device='pulsesink'

Jack:
./sampledrawer --audio-driver=gstreamer --audio-device='jackaudiosink'

Jack without automatic port connections:
./sampledrawer --audio-driver=gstreamer --audio-device='jackaudiosink connect=0'

Add an effect ('freeverb' Reverberation/room effect in this case) before sending audio to alsa:
./sampledrawer --audio-driver=gstreamer --audio-device='freeverb ! alsasink'

For this to work GStreamer with appropriate sink and affects plugin must be installed, as well as python gobject-introspection binding and GStreamer gobject-introspection data ('python3-gi' and 'gir1.2-gstreamer-1.0' packages in Ubuntu).

**Comment by dromer** [comment]
Nice, will have a try soon!
